name: Tests

on:
  push:
    branches: [ master ]
    paths:
      - "app/**"
      - "pyproject.toml"
      - "tests/**"
  pull_request:
    branches: [ master ]
    paths:
      - "app/**"
      - "pyproject.toml"
      - "tests/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10.1"
      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - run: poetry install

      - name: "Run PyTest with coverage"
        run: poetry run pytest --cov --cov-report=xml

      - name: "Upload coverage report to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true

        timeout-minutes: 30
